spring.application.name=OrcamentoSimples

server.port=8099

spring.output.ansi.enabled=ALWAYS

# H2 Database Configuration for development
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create the database schema on startup
spring.jpa.hibernate.ddl-auto=create

# Show SQL statements in the console for debugging
spring.jpa.show-sql=true
